name: SAM

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  oas:
    name: validate oas
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: validate oas
        uses: thiyagu06/openapi-validator-action@v1
        with:
          filepath: 'spotify-tags/oas.yaml'
  build:
    needs: [oas]
    name: Build & test SAM application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: sam build --use-container -t spotify-tags/template.yaml
      - run: sam validate -t spotify-tags/template.yaml
      - uses: actions/upload-artifact@v4
        with:
          name: sam-build
          path: |
            '${{ github.WORKSPACE }}.aws-sam/'
            spotify-tags/samconfig.toml
            spotify-tags/template.yaml

  deploy-sam:
    name: Deploy SAM application
    if: ${{ github.ref == 'refs/heads/main' }} 
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - uses: actions/download-artifact@v4
        with:
          name: sam-build
          path: '${{ github.workspace }}'
      # Prevent prompts and failure when the stack is unchanged
      - run: |
          sam build -t spotify-tags/template.yaml --use-container
          sam validate -t spotify-tags/template.yaml
          sam deploy --config-file spotify-tags/samconfig.toml --no-fail-on-empty-changeset --no-confirm-changeset
